Add basic swagger setup
RandomDataOrg/RandomData pull request #24
Opened 2020-06-14 11:13 UTC by KanarekLife

fixes #19

2020-06-14 17:07 UTC, krzysztof-gwozdz requested changes

2020-06-14 17:07 UTC, krzysztof-gwozdz commented on RandomData.Api/Helpers/SwashbuckleHelper.cs
> +                .UseSwaggerUI(setup =>
Variable in this lambda is not "setup". Maybe "options" because type is SwaggerUIOptions.

2020-06-14 17:07 UTC, krzysztof-gwozdz commented on RandomData.Api/Helpers/SwashbuckleHelper.cs
> +                });
Swagger is our only website we have, so maybe we should run it instead of blank page with 404. "setup.RoutePrefix = string.Empty;" is enough to achieve that.

2020-06-14 17:07 UTC, krzysztof-gwozdz commented on RandomData.Api/Helpers/SwashbuckleHelper.cs
> +                    Title = "RandomData",
App name and version of application should be moved to configuration (appsettings)

2020-06-14 17:07 UTC, krzysztof-gwozdz commented on RandomData.Api/Helpers/SwashbuckleHelper.cs
> +                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
I think you can move these 3 lines (20-22) to separate function which describe this process, for example: "AddXmlComments".

2020-06-14 17:07 UTC, krzysztof-gwozdz commented on RandomData.Api/Helpers/SwashbuckleHelper.cs
> +namespace RandomData.Api.Helpers
Noooo, "helpers" are almost always bad idea. Sounds like everything. Entire application helps with something. Most of the time static classes like this end with just Extensions post fix.

2020-06-14 17:07 UTC, krzysztof-gwozdz commented on RandomData.Api/Helpers/SwashbuckleHelper.cs
> +        public static IServiceCollection AddSwashbuckle(this IServiceCollection serviceCollection) =>
Common name for this parameter is "services".

2020-06-14 17:07 UTC, krzysztof-gwozdz commented on RandomData.Api/Helpers/SwashbuckleHelper.cs
> +            serviceCollection.AddSwaggerGen(setup =>
Variable in this lambda is not "setup". Maybe "options" because type is SwaggerGenOptions.

2020-06-14 17:07 UTC, krzysztof-gwozdz commented on RandomData.Api/Helpers/SwashbuckleHelper.cs
> +                setup.SwaggerDoc("v1", new OpenApiInfo()
If you use an object initialization brackets are optional, can be removed.

2020-06-14 17:47 UTC, krzysztof-gwozdz approved these changes

2020-06-15 10:28 UTC, ntiany approved these changes

2020-06-15 16:12 UTC, mejtika approved these changes
I have nothing more to say.

2020-06-15 17:28 UTC, merged